---
# iOS Cache
cache:
  bundler: true
  directories:
    - ./client/Carthage
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

matrix:
  include:
  - name: "iOS Client Unit Tests"
    language: swift
    osx_image: xcode10
    xcode_project: ToDoList.xcodeproj
    xcode_scheme: ToDoList
    xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone 7
    install:
      - cd client
      - carthage bootstrap --platform iOS --cache-builds

  - name: "Kotlin Server Unit Tests"
    language: java
    jdk: oraclejdk8
    install:
      - cd server
      - ./gradlew assemble

  - name: "Kotlin Server Integration Tests"
    language: java
    jdk: oraclejdk8
    install:
      - cd server
      - ./gradlew assemble
    script:
      - make integrationtests
