language: swift
osx_image: xcode10
xcode_project: ./client/ToDoList.xcodeproj
xcode_scheme: ToDoList
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone 7
install:
  - cd client
  - make bootstrap
