cache:
  directories:
    - ./client/Carthage

matrix:
  include:
    - language: swift
      osx_image: xcode10
      xcode_project: ToDoList.xcodeproj
      xcode_scheme: ToDoList
      xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone 7
      install:
        - cd client
        - carthage bootstrap --platform iOS --cache-builds

    # Kotlin Server Unit Tests
    # - lanaguage: java
    #   jdk:
    #     - oraclejdk8
    #   install:
    #     - cd ../server
    #     - ./gradlew assemble
    #   script:
    #     - make alltests
    #   cache:
    #     bundler: true
    #     directories:
    #       - $HOME/.gradle/caches/
    #       - $HOME/.gradle/wrapper/

    # Kotlin Server IntegraTests
